apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-booking-service
  template:
    metadata:
      labels:
        app: flight-booking-service
    spec:
      containers:
      - name: flight-booking-service
        image: flight-booking-service:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
