apiVersion: v1
kind: Service
metadata:
  name: trip-postgres
  labels:
    app: trip-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: trip-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trip-postgres
spec:
  serviceName: trip-postgres
  replicas: 1
  selector:
    matchLabels:
      app: trip-postgres
  template:
    metadata:
      labels:
        app: trip-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: tripuser
            - name: POSTGRES_PASSWORD
              value: trippass
            - name: POSTGRES_DB
              value: tripdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: trip-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: trip-postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
